// netlify/functions/social-troubleshoot-chat.ts
// US-SMM-4.3.2: LLM-generated contextual troubleshooting chat messages for failed pre-flight checks.
// POST { platform, checkId, checkLabel, checkDetail }
// → { message: string }  — conversational, actionable guidance generated by LLM.

import { Handler, HandlerResponse } from '@netlify/functions';
import Anthropic from '@anthropic-ai/sdk';
import jwt from 'jsonwebtoken';

const jwtSecret = process.env.JWT_SECRET!;
const anthropic  = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const MODEL      = 'claude-haiku-4-5-20251001';

// AC: 10 re-check attempts per user per platform per 24 hours (server-side enforcement)
const RATE_LIMIT_WINDOW_MS = 24 * 60 * 60 * 1000;
const RATE_LIMIT_MAX       = 10;

// In-memory store (per function instance). Sufficient for a low-volume operation.
const rateLimitStore = new Map<string, { count: number; windowStart: number }>();

function checkRateLimit(key: string): { allowed: boolean; remaining: number } {
    const now = Date.now();
    const entry = rateLimitStore.get(key);
    if (!entry || now - entry.windowStart > RATE_LIMIT_WINDOW_MS) {
        rateLimitStore.set(key, { count: 1, windowStart: now });
        return { allowed: true, remaining: RATE_LIMIT_MAX - 1 };
    }
    if (entry.count >= RATE_LIMIT_MAX) {
        return { allowed: false, remaining: 0 };
    }
    entry.count++;
    return { allowed: true, remaining: RATE_LIMIT_MAX - entry.count };
}

export const handler: Handler = async (event): Promise<HandlerResponse> => {
    if (event.httpMethod !== 'POST') return { statusCode: 405, body: 'Method Not Allowed' };

    const cookieHeader = event.headers.cookie || '';
    const sessionToken = cookieHeader.match(/aura_session=([^;]+)/)?.[1];
    if (!sessionToken) return { statusCode: 401, body: JSON.stringify({ error: 'Unauthorized' }) };

    let userId: number;
    try {
        userId = (jwt.verify(sessionToken, jwtSecret) as { userId: number }).userId;
    } catch { return { statusCode: 401, body: JSON.stringify({ error: 'Invalid session' }) }; }

    let body: { platform?: string; checkId?: string; checkLabel?: string; checkDetail?: string; checks?: Array<{ checkId: string; checkLabel?: string; checkDetail?: string }> };
    try { body = JSON.parse(event.body || '{}'); } catch {
        return { statusCode: 400, body: JSON.stringify({ error: 'Invalid JSON' }) };
    }

    const { platform, checks } = body;
    // Support single-check (checkId) and grouped multi-check (checks[]) modes
    const singleCheckId = body.checkId;
    const isGrouped = Array.isArray(checks) && checks.length > 0;
    if (!platform || (!singleCheckId && !isGrouped)) {
        return { statusCode: 400, body: JSON.stringify({ error: 'platform and checkId (or checks[]) required' }) };
    }

    // AC3.2.3: Rate limit is per user per CHECK (not per platform) — each check gets its own 10/24h budget
    const rateLimitCheckId = isGrouped ? `grouped:${platform}` : singleCheckId!;
    const rateLimitKey = `${userId}:${rateLimitCheckId}`;
    const { allowed, remaining } = checkRateLimit(rateLimitKey);
    if (!allowed) {
        return {
            statusCode: 429,
            headers: { 'X-RateLimit-Remaining': '0' },
            body: JSON.stringify({ error: 'Rate limit reached — please wait 24 hours before re-checking again.', rateLimited: true }),
        };
    }

    const platformLabels: Record<string, string> = {
        instagram: 'Instagram & Facebook', facebook: 'Facebook', linkedin: 'LinkedIn', x: 'X (Twitter)',
    };
    const platformLabel = platformLabels[platform.toLowerCase()] ?? platform;

    // AC3.2.1: Group multiple failures into a single coherent message
    let prompt: string;
    if (isGrouped) {
        const checkList = checks!.map(c => `- ${c.checkId}: ${c.checkLabel ?? 'Unknown'} — ${c.checkDetail ?? 'No detail'}`).join('\n');
        prompt = `You are a friendly social media setup assistant helping a small business owner troubleshoot their ${platformLabel} integration.

The following pre-flight configuration checks have failed:
${checkList}

Write a short, conversational, encouraging message (3–4 sentences max) that:
1. Acknowledges what was being set up
2. Groups the issues together in plain English without technical jargon — do not list them individually
3. Gives the single most important next step they should take right now
4. Ends on an encouraging note

Do not mention check IDs. Do not use bullet points. Write naturally as if you're a helpful colleague explaining the situation.`;
    } else {
        prompt = `You are a friendly social media setup assistant helping a small business owner troubleshoot their ${platformLabel} integration.

The following pre-flight configuration check has failed:
Check: ${singleCheckId} — ${body.checkLabel ?? 'Unknown check'}
Reason: ${body.checkDetail ?? 'No detail provided.'}

Write a short, conversational, encouraging message (2–3 sentences max) that:
1. Acknowledges the specific issue without being technical or alarming
2. Gives one clear, actionable next step they can take right now
3. Ends on an encouraging note

Do not mention check IDs. Do not use bullet points. Write naturally as if you're a helpful colleague talking them through it.`;
    }

    try {
        const response = await anthropic.messages.create({
            model: MODEL,
            max_tokens: 200,
            messages: [{ role: 'user', content: prompt }],
        });
        const message = (response.content[0] as { text: string }).text.trim();
        return {
            statusCode: 200,
            headers: { 'Content-Type': 'application/json', 'X-RateLimit-Remaining': String(remaining) },
            body: JSON.stringify({ message, remaining }),
        };
    } catch (err) {
        console.error('[social-troubleshoot-chat] LLM error:', err);
        return { statusCode: 500, body: JSON.stringify({ error: 'Could not generate troubleshooting message' }) };
    }
};
