// netlify/functions/social-troubleshoot-chat.ts
// US-SMM-4.3.2: LLM-generated contextual troubleshooting chat messages for failed pre-flight checks.
// POST { platform, checkId, checkLabel, checkDetail }
// → { message: string }  — conversational, actionable guidance generated by LLM.

import { Handler } from '@netlify/functions';
import Anthropic from '@anthropic-ai/sdk';
import jwt from 'jsonwebtoken';

const jwtSecret = process.env.JWT_SECRET!;
const anthropic  = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const MODEL      = 'claude-haiku-4-5-20251001';

// AC: 10 re-check attempts per user per platform per 24 hours (server-side enforcement)
const RATE_LIMIT_WINDOW_MS = 24 * 60 * 60 * 1000;
const RATE_LIMIT_MAX       = 10;

// In-memory store (per function instance). Sufficient for a low-volume operation.
const rateLimitStore = new Map<string, { count: number; windowStart: number }>();

function checkRateLimit(key: string): { allowed: boolean; remaining: number } {
    const now = Date.now();
    const entry = rateLimitStore.get(key);
    if (!entry || now - entry.windowStart > RATE_LIMIT_WINDOW_MS) {
        rateLimitStore.set(key, { count: 1, windowStart: now });
        return { allowed: true, remaining: RATE_LIMIT_MAX - 1 };
    }
    if (entry.count >= RATE_LIMIT_MAX) {
        return { allowed: false, remaining: 0 };
    }
    entry.count++;
    return { allowed: true, remaining: RATE_LIMIT_MAX - entry.count };
}

export const handler: Handler = async (event) => {
    if (event.httpMethod !== 'POST') return { statusCode: 405, body: 'Method Not Allowed' };

    const cookieHeader = event.headers.cookie || '';
    const sessionToken = cookieHeader.match(/aura_session=([^;]+)/)?.[1];
    if (!sessionToken) return { statusCode: 401, body: JSON.stringify({ error: 'Unauthorized' }) };

    let userId: number;
    try {
        userId = (jwt.verify(sessionToken, jwtSecret) as { userId: number }).userId;
    } catch { return { statusCode: 401, body: JSON.stringify({ error: 'Invalid session' }) }; }

    let body: { platform?: string; checkId?: string; checkLabel?: string; checkDetail?: string };
    try { body = JSON.parse(event.body || '{}'); } catch {
        return { statusCode: 400, body: JSON.stringify({ error: 'Invalid JSON' }) };
    }

    const { platform, checkId, checkLabel, checkDetail } = body;
    if (!platform || !checkId) {
        return { statusCode: 400, body: JSON.stringify({ error: 'platform and checkId required' }) };
    }

    // AC: 10-attempt rate limit per user per platform per 24h
    const rateLimitKey = `${userId}:${platform}`;
    const { allowed, remaining } = checkRateLimit(rateLimitKey);
    if (!allowed) {
        return {
            statusCode: 429,
            headers: { 'X-RateLimit-Remaining': '0' },
            body: JSON.stringify({ error: 'Rate limit reached — please wait 24 hours before re-checking again.', rateLimited: true }),
        };
    }

    const platformLabels: Record<string, string> = {
        instagram: 'Instagram & Facebook', facebook: 'Facebook', linkedin: 'LinkedIn', x: 'X (Twitter)',
    };
    const platformLabel = platformLabels[platform.toLowerCase()] ?? platform;

    const prompt = `You are a friendly social media setup assistant helping a small business owner troubleshoot their ${platformLabel} integration.

The following pre-flight configuration check has failed:
Check: ${checkId} — ${checkLabel ?? 'Unknown check'}
Reason: ${checkDetail ?? 'No detail provided.'}

Write a short, conversational, encouraging message (2–3 sentences max) that:
1. Acknowledges the specific issue without being technical or alarming
2. Gives one clear, actionable next step they can take right now
3. Ends on an encouraging note

Do not mention check IDs. Do not use bullet points. Write naturally as if you're a helpful colleague talking them through it.`;

    try {
        const response = await anthropic.messages.create({
            model: MODEL,
            max_tokens: 200,
            messages: [{ role: 'user', content: prompt }],
        });
        const message = (response.content[0] as { text: string }).text.trim();
        return {
            statusCode: 200,
            headers: { 'Content-Type': 'application/json', 'X-RateLimit-Remaining': String(remaining) },
            body: JSON.stringify({ message, remaining }),
        };
    } catch (err) {
        console.error('[social-troubleshoot-chat] LLM error:', err);
        return { statusCode: 500, body: JSON.stringify({ error: 'Could not generate troubleshooting message' }) };
    }
};
