// src/config/compliance.ts
//
// Epic AC-ai-compliance / AC4.1 — Modular Compliance Layer.
//
// SINGLE SOURCE OF TRUTH for every AI-regulatory threshold and rule (EU AI Act + US state/
// federal). Compliance is a system standard, NOT scattered constants: changing a threshold —
// the EU jurisdiction list, a risk-tier keyword, the systemic-risk compute trigger, a
// disclosure string — happens HERE (a configuration file) or via a `platform_config` override
// at runtime, with NO change to core algorithmic code. Call sites import these values; they
// must never re-declare their own copy.
//
// Two layers:
//   1. Static defaults below — versioned, the "configuration file" the AC asks for.
//   2. Async `getEffective*()` accessors — overlay an admin `platform_config` override on the
//      static default so the most volatile thresholds can change without a redeploy.

import { CONFIG_KEYS, getPlatformConfig } from '../utils/platform-config';

/** Bump when any value below changes — surfaced in audit/provenance exports for traceability. */
export const COMPLIANCE_CONFIG_VERSION = '2026-06-23';

// ── EU AI Act jurisdiction ────────────────────────────────────────────────────
// The 27 EU member states (ISO-3166 alpha-2; Greece as 'GR' to match Stripe/Netlify country
// codes). EU-jurisdiction workspaces get Art. 50 disclosure defaults turned on. This list was
// previously copy-pasted into register.ts, onboarding.ts, workspace-ai-disclosure.ts and
// provision-assistant-async.ts — they now all import EU_MEMBER_STATE_SET / isEuCountry.
export const EU_MEMBER_STATES = [
    'AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GR', 'HR', 'HU',
    'IE', 'IT', 'LT', 'LU', 'LV', 'MT', 'NL', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK',
] as const;

export const EU_MEMBER_STATE_SET: ReadonlySet<string> = new Set(EU_MEMBER_STATES);

/** True if the (case-insensitive) ISO country code is an EU member state. */
export function isEuCountry(code: string | null | undefined): boolean {
    return !!code && EU_MEMBER_STATE_SET.has(code.trim().toUpperCase());
}

// ── Transparency & disclosure (EU AI Act Art. 50 / 52; US state labelling laws) ─
// Centralised default disclosure copy. Per-surface because each renders differently:
//   - emailFooterDefault: per-assistant outbound email footer ([[ai-email-footer]]).
//   - workspaceFooterDefault: workspace-wide footer (Art. 50, My Account toggle).
//   - uiLabelDefault: user-facing "this is AI" label component (AC1.2).
export const DISCLOSURE = {
    emailFooterDefault:
        '--- This message was drafted with AI assistance by [Assistant Name]. Please verify any factual claims before acting.',
    workspaceFooterDefault: 'This message was composed with AI assistance.',
    uiLabelDefault: 'Generated by Be More Swan AI',
    /** AC2.1 — explicit upfront notice when a user starts talking to a conversational agent. */
    conversationalAgentNotice:
        'You are chatting with an AI assistant, not a human. Responses are generated automatically.',
} as const;

// ── Risk tiering (EU AI Act Art. 6 + Annex III; Art. 5 prohibited practices) ────
export type RiskTier = 'minimal' | 'limited' | 'high_risk' | 'prohibited';

// Annex III high-risk domains — keyword heuristics that SUGGEST a high-risk classification
// (employment screening, credit scoring, etc.). A suggestion only: a human still confirms the
// definitive `masterAssistants.riskClassification`. Previously inline in manage-risk-assessment.ts.
export const HIGH_RISK_KEYWORDS = [
    'Lead Screener', 'HR Assistant', 'Recruitment', 'Recruiter', 'Hiring',
    'Credit Scoring', 'Creditworthiness', 'Loan', 'Insurance Pricing',
    'Biometric', 'Emotion', 'Background Check', 'Worker Management',
] as const;

// Art. 5 — practices that are outright PROHIBITED in the EU. Matching one of these blocks
// deployment entirely (no assessment can clear it).
export const PROHIBITED_KEYWORDS = [
    'Social Scoring', 'Social Credit', 'Predictive Policing',
    'Emotion Recognition Workplace', 'Subliminal Manipulation', 'Untargeted Scraping',
] as const;

const includesAny = (haystack: string, needles: readonly string[]): boolean => {
    const h = haystack.toLowerCase();
    return needles.some(n => h.includes(n.toLowerCase()));
};

/**
 * Heuristic first-pass risk tier from an assistant's name + category. Returns the SUGGESTED
 * tier; the authoritative value is the human-confirmed masterAssistants.riskClassification.
 */
export function classifyRiskByKeywords(name: string, category: string): RiskTier {
    const text = `${name} ${category}`;
    if (includesAny(text, PROHIBITED_KEYWORDS)) return 'prohibited';
    if (includesAny(text, HIGH_RISK_KEYWORDS)) return 'high_risk';
    return 'limited';
}

/** Convenience boolean used by the assessment UI to nudge an admin toward an assessment. */
export function suggestsHighRisk(name: string, category: string): boolean {
    const tier = classifyRiskByKeywords(name, category);
    return tier === 'high_risk' || tier === 'prohibited';
}

// ── General-purpose AI systemic-risk compute trigger (EU AI Act Art. 51) ────────
// A GPAI model trained above this many floating-point operations is presumed to carry
// "systemic risk". Config-driven so the threshold can be retuned as the Commission updates it,
// without touching code that consumes it. Default = the Act's current 10^25 FLOP figure.
export const SYSTEMIC_RISK_FLOP_THRESHOLD = 1e25;

// ── Biometric categorisation / emotion recognition (Art. 5 / Art. 52) ───────────
// AC2.2 — none are integrated today, so the capability is OFF by default and must stay gated
// behind explicit upfront consent if ever enabled. Flipping `enabled` here is the single switch.
export const BIOMETRIC_EMOTION = {
    enabled: false,
    requiresExplicitConsent: true,
} as const;

// ── Watermarking / provenance (EU AI Act Art. 50(2)) ────────────────────────────
export const WATERMARK = {
    c2paSchemaVersion: '1.0',
    // Text/post generation records a C2PA-style provenance entry today ([[content-provenance]]).
    recordProvenanceForText: true,
    // No AI image/audio/video generation exists yet; when it lands, embed a C2PA manifest into
    // the media bytes before output. This flag is the gate that switch wires into.
    embedInGeneratedMedia: true,
} as const;

// ── Public-interest text gate (AC1.3) ───────────────────────────────────────────
// Text touching these topics must carry a visible AI-disclosure label OR pass a human-editorial
// sign-off gate before publication. Tune the topic list here as guidance evolves.
export const PUBLIC_INTEREST_TOPICS = [
    'election', 'vote', 'referendum', 'ballot',
    'vaccine', 'public health', 'pandemic', 'outbreak',
    'immigration', 'asylum', 'climate policy', 'legislation', 'court ruling',
] as const;

/** True when generated text appears to touch a public-interest matter (AC1.3 trigger). */
export function isPublicInterestText(text: string | null | undefined): boolean {
    return !!text && includesAny(text, PUBLIC_INTEREST_TOPICS);
}

// ── Runtime overrides (layer 2) ─────────────────────────────────────────────────
// Overlay a platform_config override on a static default so an admin can retune the most
// volatile thresholds without a redeploy. Falls back to the static default when unset.

/**
 * Effective EU jurisdiction set: static 27 members UNION any extra codes an admin configured
 * (e.g. EEA additions). Never shrinks below the statutory list.
 */
export async function getEffectiveEuCountries(): Promise<ReadonlySet<string>> {
    const extra = (await getPlatformConfig(CONFIG_KEYS.COMPLIANCE_EU_EXTRA_COUNTRIES)) as string[] | null;
    if (!extra?.length) return EU_MEMBER_STATE_SET;
    return new Set([...EU_MEMBER_STATES, ...extra.map(c => c.trim().toUpperCase())]);
}

/** Effective systemic-risk FLOP threshold (admin-overridable). */
export async function getSystemicRiskFlopThreshold(): Promise<number> {
    const override = (await getPlatformConfig(CONFIG_KEYS.COMPLIANCE_SYSTEMIC_RISK_FLOPS)) as number | null;
    return typeof override === 'number' && override > 0 ? override : SYSTEMIC_RISK_FLOP_THRESHOLD;
}
